v = 0.5
a = 0.5
pose_init = [1.57, -1.744, 1.57, 4.7102, 4.7102, 4.3602]
global ready = False
write_output_integer_register(0, 0)

def inicio():
    global joints =  pose_init
    movej(joints, a, v)
    ready = True
    global flag = False
    write_output_integer_register(0, 1)
end

def updateActionRTDE():
    global action = [1.57, -1.744, 1.57, 4.7102, 4.7102, 4.3602]
    i=0
    q= get_actual_joint_positions()
    while i<6:
        action[i] = read_input_float_register(i)
        i = i + 1
    end
    return action
end

# Definicion del programa principal.
def main_program():
    while ready == False or get_digital_out(2) == False or read_input_integer_register(0) == 0:
        if(ready == False):
            inicio()
        else:
            sync()
        end
    end
    while get_digital_out(2) == True and read_input_integer_register(0) == 1:
        sync()
        global flag = True
        joints = updateActionRTDE()
        movej(joints, a, v)
        pose = get_actual_tcp_pose()
        rpy=rotvec2rpy([pose[3], pose[4], pose[5]])
        global roll = rpy[0]
        global pitch = rpy[1]
        global yaw = rpy[2]
    end
    write_output_integer_register(0, 0)
    sync()
end

main_program()
