v = 0.5
a = 0.5
pose_init = [1.57, -1.744, 1.57, 4.7102, 4.7102, 4.3602]
global ready = False
write_output_integer_register(0, 0)

def inicio():
    global joints =  pose_init
    movej(joints, a, v)
    ready = True
    global flag = False
    write_output_integer_register(0, 1)
end

def updateActionRTDE():
    global action = [1.57, -1.744, 1.57, 4.7102, 4.7102, 4.3602]
    i=0
    q= get_actual_joint_positions()
    while i<6:
        target = read_input_float_register(i)
        diff= (target - q[i] + 3.1416) % (2*3.1416) - 3.1416
        action[i]=target+diff
        i = i + 1
    end
    return action
end

# Definicion del programa principal.
def main_program():
    while ready == False or get_digital_out(2) == False or read_input_integer_register(0) == 0:
        if(ready == False):
            inicio()
        else:
            sync()
        end
    end
    while get_digital_out(2) == True and read_input_integer_register(0) == 1:
        sync()
        global flag = True
        joints = updateActionRTDE()
        servoj(joints, t=0.01, lookahead_time=0.3, gain=200)
    end
    write_output_integer_register(0, 0)
    sync()
end

main_program()
